language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - alberto_nitro_eso@hotmail.com
script:
- mvn verify 
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify 
- mvn sonar:sonar -Dsonar.organization=albertonitro-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR 
